server:
  port: 8081
spring:
  application:
    name: reviewSite
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///review_site?useSSL=false&serverTimezone=UTC
    username: root
    password: liyu.110
  redis:
    host: 172.19.208.148
    port: 6379
    password: liyu.110
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.liyu.entity # 别名扫描包
logging:
  level:
    com.liyu: debug